services:
  - type: web
    name: sece-chatbot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: AUDIO_CLEANUP_HOURS
        value: "2"
      - key: PYTHON_VERSION
        value: "3.11.0"
